export const COUNTRY_NAME_TO_ID: Record<string, string> = {
  algeria: 'DZ',
  angola: 'AO',
  australia: 'AU',
  benin: 'BJ',
  botswana: 'BW',
  brazil: 'BR',
  'burkina faso': 'BF',
  burkina: 'BF',
  burundi: 'BI',
  cameroon: 'CM',
  canada: 'CA',
  'cape verde': 'CV',
  'central african republic': 'CF',
  'central african': 'CF',
  chad: 'TD',
  china: 'CN',
  comoros: 'KM',
  'côte d\'ivoire': 'CI',
  'cote d\'ivoire': 'CI',
  'ivory coast': 'CI',
  ivory: 'CI',
  'dr congo': 'CD',
  'democratic republic of the congo': 'CD',
  'democratic republic': 'CD',
  drc: 'CD',
  djibouti: 'DJ',
  egypt: 'EG',
  'equatorial guinea': 'GQ',
  eritrea: 'ER',
  eswatini: 'SZ',
  swaziland: 'SZ',
  ethiopia: 'ET',
  france: 'FR',
  gabon: 'GA',
  gambia: 'GM',
  germany: 'DE',
  ghana: 'GH',
  guinea: 'GN',
  'guinea-bissau': 'GW',
  india: 'IN',
  japan: 'JP',
  kenya: 'KE',
  lesotho: 'LS',
  liberia: 'LR',
  libya: 'LY',
  madagascar: 'MG',
  malawi: 'MW',
  mali: 'ML',
  mauritania: 'MR',
  mauritius: 'MU',
  morocco: 'MA',
  mozambique: 'MZ',
  namibia: 'NA',
  niger: 'NE',
  nigeria: 'NG',
  'republic of the congo': 'CG',
  rwanda: 'RW',
  senegal: 'SN',
  seychelles: 'SC',
  'sierra leone': 'SL',
  somalia: 'SO',
  'south africa': 'ZA',
  'south sudan': 'SS',
  sudan: 'SD',
  'são tomé and príncipe': 'ST',
  'sao tome and principe': 'ST',
  'sao tome': 'ST',
  tanzania: 'TZ',
  togo: 'TG',
  tunisia: 'TN',
  uganda: 'UG',
  'united kingdom': 'GB',
  uk: 'GB',
  britain: 'GB',
  england: 'GB',
  'united states': 'US',
  usa: 'US',
  america: 'US',
  'western sahara': 'EH',
  zambia: 'ZM',
  zimbabwe: 'ZW',
};